-- Create a medication table with the following columns.
-- MedicationID,
-- Name,
-- Brand,

CREATE TABLE IF NOT EXISTS public.medication
(
    "MedicationID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" character varying COLLATE pg_catalog."default",
    "Brand" character varying COLLATE pg_catalog."default",
    CONSTRAINT medication_pkey PRIMARY KEY ("MedicationID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.medication
    OWNER to postgres;