-- Create a “prescription” table with the following columns. 
-- Make sure to implement to correct table relation between prescription,
-- patient and physician tables (this means adding the appropriate constraints)

-- PhysicianID,
-- PatientRecordNumber
-- MedicationID,
-- PrescribedOn,
-- AppointmentID,
-- Dosage

CREATE TABLE IF NOT EXISTS public.prescription
(
    "PrescriptionID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PhysicianID" bigint NOT NULL,
    "PatientRecordNumber" bigint NOT NULL,
    "MedicationID" bigint NOT NULL,
    "PrescribedOn" timestamp with time zone NOT NULL,
    "AppointmentID" bigint NOT NULL,
    "Dosage" smallint NOT NULL,
    CONSTRAINT prescription_pkey PRIMARY KEY ("PrescriptionID"),
    CONSTRAINT fk_appointment FOREIGN KEY ("AppointmentID")
        REFERENCES public.appointment ("AppointmentID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_medication FOREIGN KEY ("MedicationID")
        REFERENCES public.medication ("MedicationID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_patient_record_number FOREIGN KEY ("PatientRecordNumber")
        REFERENCES public.patient ("PatientRecordNumber") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_physician FOREIGN KEY ("PhysicianID")
        REFERENCES public.physician ("PhysicianID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.prescription
    OWNER to postgres;