-- Table: public.nurse

-- DROP TABLE IF EXISTS public.nurse;

CREATE TABLE IF NOT EXISTS public.nurse
(
    "NurseID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PhysicianID" bigint NOT NULL,
    "PatientRecordNumber" bigint NOT NULL,
    CONSTRAINT nurse_pkey PRIMARY KEY ("NurseID"),
    CONSTRAINT fk_patient FOREIGN KEY ("PatientRecordNumber")
        REFERENCES public.patient ("PatientRecordNumber") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_physician FOREIGN KEY ("PhysicianID")
        REFERENCES public.physician ("PhysicianID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.nurse
    OWNER to postgres;