-- Table: public.employee
--Create Employee table with the following columns
--Employee ID unique number autoincrement
--First Name
--LastName
--DepartmentID
--Title
--Phone Number
--Email
--ManagerID
-- DROP TABLE IF EXISTS public.employee;

CREATE TABLE IF NOT EXISTS public.employee
(
    "EmployeeID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "FirstName" character varying COLLATE pg_catalog."default" NOT NULL,
    "LastName" character varying COLLATE pg_catalog."default" NOT NULL,
    "DepartmentID" bigint NOT NULL,
    "Title" character varying COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" bigint NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "ManagerID" bigint NOT NULL,
    CONSTRAINT employee_pkey PRIMARY KEY ("EmployeeID"),
    CONSTRAINT fk_department FOREIGN KEY ("DepartmentID")
        REFERENCES public.department ("DepartmentID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.employee
    OWNER to postgres;