-- Table: public.manager
--Refer to Department types created in Hospital ID table ('admissions', 'administration','food_hospitality','diagnostic_imaging','emergency','cardiology', 'neurology', 'oncology', 'pediatrics', 'ICU', 'surgery', 'maternity', 'mental_health', 'billing')
--Create Manager types (supervisor, manager, department head)

--Create Manager table with the following columns
--Manager ID autoincrement number
--Manager Type
--DepartmentID
--Department Type
--EmployeeID
--FirstName
--LastName
--Phone Number
--Email

-- DROP TABLE IF EXISTS public.manager;

CREATE TABLE IF NOT EXISTS public.manager
(
    "ManagerID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "ManagerType" _managertype NOT NULL,
    "DepartmentID" bigint NOT NULL,
    "DepartmentType" _departmenttype NOT NULL,
    "EmployeeID" bigint NOT NULL,
    "FirstName" character varying COLLATE pg_catalog."default" NOT NULL,
    "LastName" character varying COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" bigint NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT manager_pkey PRIMARY KEY ("ManagerID"),
    CONSTRAINT fk_employee FOREIGN KEY ("EmployeeID")
        REFERENCES public.employee ("EmployeeID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.manager
    OWNER to postgres;