-- Table: public.department
--Refer to Department types created in Hospital table ('admissions', 'administration','food_hospitality','diagnostic_imaging','emergency','cardiology', 'neurology', 'oncology', 'pediatrics', 'ICU', 'surgery', 'maternity', 'mental_health', 'billing')
--Refer to Manager types created in Manager table(supervisor, manager, department head)
--Refer to Locations created in Hospital Table (A wing, B wing, C wing, D wing, E wing)

--Create Department table with the following columns
--Department ID autoincrement number
--Department Type
--ManagerID
--ManagerType exclusively department head
--FirstName
--LastName
--Phone Number
--Email
--Location

-- DROP TABLE IF EXISTS public.department;

CREATE TABLE IF NOT EXISTS public.department
(
    "DepartmentID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "DepartmentType" _departmenttype NOT NULL,
    "ManagerID" bigint NOT NULL,
    "ManagerType" _managertype NOT NULL,
    "FirstName" character varying COLLATE pg_catalog."default" NOT NULL,
    "LastName" character varying COLLATE pg_catalog."default" NOT NULL,
    "PhoneNumber" bigint NOT NULL,
    "Email" character varying COLLATE pg_catalog."default" NOT NULL,
    "Location" _location,
    CONSTRAINT department_pkey PRIMARY KEY ("DepartmentID"),
    CONSTRAINT fk_manager FOREIGN KEY ("ManagerID")
        REFERENCES public.manager ("ManagerID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT department_head_manager_only CHECK ("ManagerType" = 'Department_head'::_managertype)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.department
    OWNER to postgres;